# options for analysis running
run:
  go: "1.23"
  skip-dirs:
    - tmp
  skip-files:
    - ".*_test.go"

  # default concurrency is a available CPU number
  concurrency: 4

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 10m

# all available settings of specific linters
linters-settings:
  errcheck:
    # report about not checking of errors in type assertions: `a := b.(MyStruct)`;
    check-type-assertions: true
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    check-blank: true
  govet:
    # report about shadowed variables
    check-shadowing: true
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 30
  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 300
  unused:
    # treat code as a program (not a library) and report unused exported identifiers
    check-exported: true
  unparam:
    # Inspect exported functions, default is false. Set to true if no external program/library imports your code.
    check-exported: true
  nakedret:
    # make an issue if func has more lines of code than this setting and it has naked returns
    max-func-lines: 60
  prealloc:
    # Report preallocation suggestions only on simple loops that have no returns/breaks/continues/gotos in them.
    simple: true
    range-loops: true # Report preallocation suggestions on range loops
    for-loops: false # Report preallocation suggestions on for loops

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gocyclo
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused
  fast: false

issues:
  exclude-files:
    - ".*_test.go"
  exclude-dirs:
    - tmp
  exclude-rules:
    - linters:
        - revive
      text: "unexported-return"
    - linters:
        - revive
      text: "don't use an underscore in package name"
    - linters:
        - gocritic
      text: "commentFormatting: put a space between `//` and comment text"

    - linters:
        - staticcheck
      text: "should not use built-in type string as key for value"
